name: manual-populate
on: [workflow_dispatch]
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call populate api endpoint
        run: |
          curl --request POST \
          --url 'https://www.sat-vis.app/api/populate' \
          --header 'Authorization: ${{ secrets.POPULATE_KEY }}'
